# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_no', models.CharField(max_length=20)),
                ('style_year', models.IntegerField()),
                ('style_season', models.CharField(max_length=2)),
                ('order_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
