# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='site',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='style',
            name='order_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='style',
            name='style_no',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='style_season',
            field=models.CharField(default='', max_length=2),
        ),
    ]
