# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170201_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('spec', models.CharField(blank=True, default='', max_length=64)),
                ('unit', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.SmallIntegerField(default=0)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rawmaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('ordered_at', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateField(blank=True, null=True)),
                ('stocked_at', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='style',
            name='saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='style',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='style',
            name='site',
            field=models.SmallIntegerField(choices=[(1, 'vina'), (2, 'bg')], default=1),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Style'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Supplier'),
        ),
    ]
