# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170202_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rawmaterials',
            new_name='Rawmaterial',
        ),
    ]
